param(
    [string]$TraitDirectory = 'C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings III\game\common\traits',
    [string]$EnglishLocalizationDirectory = 'C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings III\game\localization\english',
    [string]$ModDirectory = (Split-Path -Parent $PSScriptRoot),
    [int]$ResultSlots = 8
)

$traitKeys = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

Get-ChildItem -LiteralPath $TraitDirectory -Filter '*.txt' -File | ForEach-Object {
    $depth = 0
    foreach ($line in Get-Content -LiteralPath $_.FullName) {
        $content = $line -replace '#.*$', ''
        if ($depth -eq 0 -and $content -match '^\s*([A-Za-z0-9_]+)\s*=\s*\{') {
            [void]$traitKeys.Add($Matches[1])
        }
        $depth += ([regex]::Matches($content, '\{')).Count
        $depth -= ([regex]::Matches($content, '\}')).Count
    }
}

$localizationKeyToTrait = @{}
foreach ($traitKey in $traitKeys) {
    $localizationKeyToTrait[$traitKey] = $traitKey
    $localizationKeyToTrait["trait_$traitKey"] = $traitKey
}

$traitDisplayNames = @{}
Get-ChildItem -LiteralPath $EnglishLocalizationDirectory -Filter '*.yml' -File -Recurse | ForEach-Object {
    foreach ($line in Get-Content -LiteralPath $_.FullName) {
        if ($line -match '^\s*([A-Za-z0-9_]+):\d*\s+"([^"]*)"') {
            $localizationKey = $Matches[1]
            if ($localizationKeyToTrait.ContainsKey($localizationKey)) {
                $traitDisplayNames[$localizationKeyToTrait[$localizationKey]] = $Matches[2]
            }
        }
    }
}

$aliases = @{}
foreach ($traitKey in $traitKeys) {
    $searchTerms = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    [void]$searchTerms.Add($traitKey)
    foreach ($part in $traitKey.Split('_')) {
        [void]$searchTerms.Add($part)
    }
    if ($traitDisplayNames.ContainsKey($traitKey)) {
        foreach ($wordMatch in [regex]::Matches($traitDisplayNames[$traitKey], '[A-Za-z0-9]+')) {
            [void]$searchTerms.Add($wordMatch.Value)
        }
    }

    foreach ($term in $searchTerms) {
        $normalizedTerm = $term.ToLowerInvariant()
        for ($length = 1; $length -le $normalizedTerm.Length; $length++) {
            $prefix = $normalizedTerm.Substring(0, $length)
            if (-not $aliases.ContainsKey($prefix)) {
                $aliases[$prefix] = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
            }
            [void]$aliases[$prefix].Add($traitKey)
        }
    }
}

$languages = @(
    @{ Folder = 'english'; Header = 'l_english:' },
    @{ Folder = 'french'; Header = 'l_french:' },
    @{ Folder = 'german'; Header = 'l_german:' },
    @{ Folder = 'korean'; Header = 'l_korean:' },
    @{ Folder = 'russian'; Header = 'l_russian:' },
    @{ Folder = 'simp_chinese'; Header = 'l_simp_chinese:' },
    @{ Folder = 'spanish'; Header = 'l_spanish:' }
)

# CK3 reports localization hash collisions at load time. Keep known collisions out
# of the generated index; losing one low-priority result slot is harmless.
$excludedLocalizationKeys = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
[void]$excludedLocalizationKeys.Add('accou_trait_alias_06_EDUCATI')

foreach ($language in $languages) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add($language.Header)
    $lines.Add(' # Generated by tools/generate_trait_search_aliases.ps1. Do not edit by hand.')

    foreach ($prefix in ($aliases.Keys | Sort-Object)) {
        $matches = @($aliases[$prefix] | Sort-Object | Select-Object -First $ResultSlots)
        $queryForms = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
        [void]$queryForms.Add($prefix)
        [void]$queryForms.Add(($prefix.Substring(0, 1).ToUpperInvariant() + $prefix.Substring(1)))
        [void]$queryForms.Add($prefix.ToUpperInvariant())

        foreach ($query in $queryForms) {
            for ($slot = 0; $slot -lt $matches.Count; $slot++) {
                $slotNumber = ($slot + 1).ToString('00')
                $localizationKey = "accou_trait_alias_${slotNumber}_${query}"
                if (-not $excludedLocalizationKeys.Contains($localizationKey)) {
                    $lines.Add(" ${localizationKey}:0 `"$($matches[$slot])`"")
                }
            }
        }
    }

    $output = Join-Path $ModDirectory "localization\$($language.Folder)\accou_trait_search_aliases_l_$($language.Folder).yml"
    $lines | Set-Content -LiteralPath $output -Encoding utf8
}

Write-Output "Generated aliases for $($traitKeys.Count) traits and $($aliases.Count) search prefixes."
